### ISSUE TITLE
Figure out why the shex stuff is not working in the fork

### ISSUE THREAD

**Issue by addshore** [wbstack/cradle#2]
Reported on telegram.

An initial poke was made in https://github.com/wbstack/cradle/pull/1 which fixed 1 thing, but left some parts still not working.

https://twitter.com/MagnusManske/status/1375375390135439362

> OAuth permission error it seems:
> The authorization headers in your request are not valid: No approved grant was found for that authorization token. See https://addshore-alpha.wiki.opencura.com/w/api.php for API usage."
> 
> So api.php reads in the same config as the JS frontend, but that is config.js, so I fiddle with the JS code in PHP to make a “pure” JSON file. All that window.location.protocol stuff in your config.js breaks that.

**Comment by addshore** [comment]
So it looks like a hack will also be needed in https://github.com/wbstack/cradle/blob/main/public_html/api.php#L8-L15

**Comment by addshore** [comment]
I took an initial look at this, but still more to do.
Tools like this would be easier to work with if their auth was not split out over widar and the tool itself.
Right now all that might be needed is `WbstackMagnusOauth::setOauthDetails` in api.php, but this api lives in cradle, but the other authed stuff is currently in widar...

**Comment by GreenReaper** [comment]
I debugged through this and after a while I figured out what was necessary to get it to work, and some ways it might be improved.

The error message above occurs if you are not logged in via the tool; but even when you are, there is a problem in that valid shapes specified without EXTRA - including your shape `<something> { wdt:P12 [wd:Q1] }` - or with non-wdt: prefixes aren't loaded.

After some poking (vue.js loads shex as a dynamic component, harder to debug) [I found this regex](https://github.com/wbstack/cradle/blob/main/public_html/vue_components/shex-page.html#L96) was failing to find any elements:
> <([^/<>]+)>(?: EXTRA .*?)?\w*\{(.+?)\}

[As Lucas notes](https://twitter.com/LucasWerkmeistr/status/1227544886309773312) "the regex currently treats EXTRA as a mandatory part of a shape, should be optional". In fact, [an attempt was made to make the EXTRA into an optional non-capturing group](https://github.com/wbstack/cradle/commit/53b0e44f9b0f49bac547d0bf890d946a73cc4376); regardless, it does not actually work without it in many cases because \s is not included in \w and therefore any white space between `>` and `{` will break the match.

As I understand it, [the EXTRA portion indicates that it is OK to have additional use of predicates not mentioned as part of the shape](https://shex.io/shex-primer/#extra-properties). For example, I believe this means that [humans](https://www.wikidata.org/wiki/EntitySchema:E10) may be an _instance of_ (P31) items other than a human.
> &lt;human&gt; EXTRA wdt:P31 {
>    wdt:P31 [wd:Q5];
> ... }

[I had a shape](https://furry.wiki.opencura.com/wiki/EntitySchema:E1) with `<convention> {` that was not detected.
When I changed it to `<convention> EXTRA wfdt:P1 {` it proceeded through that particular issue.

The regex `<([^/<>]+)>(?:\s+EXTRA\s+.*?)?\s*\w*\s*\{(.+?)\}` seems to work for both [the CLOSED case, one or more EXTRA wdt:, or none](http://shex.io/shex-semantics/#prod-shapeDefinition) and may resolve this issue. (There may however be a simpler alternative; and I cannot guarantee it works in all cases.)

However, I then ran into the fact that I _wasn't_ using `wdt:` but rather `wfdt:` to refer to direct local properties. I did this in part because [these are mentioned as being "internal to Wikidata"](https://en.wikibooks.org/wiki/SPARQL/Prefixes) and may be confused with Wikidata, especially when working with multiple wikibases or performing a federated query.

Unfortunately [Cradle is hardcoded to match](https://github.com/wbstack/cradle/blob/main/public_html/vue_components/shex-page.html#L103) via `part.match(/^wdt:(P\d+)\s*(.*)$/) ;` and so failed to find the direct props.

My schema contained `PREFIX wfdt: <http://furry.wiki.opencura.com/prop/direct/>` and it worked in the ShEx2 validator. Ideally Cradle might have looked for a prefix declaration with a path matching the value of `d.query.general.server + '/prop/direct/'` saved during its custom API step. (The same place where `self.page_path` is incorrectly set, as mentioned below.)

[Once I had modified my shape to use wdt/wd](https://furry.wiki.opencura.com/wiki/EntitySchema:E2), [Cradle loaded the shape successfully](https://furry.wiki.opencura.com/tools/cradle/?#/shex/E2). However, the component '[typeahead-search](https://furry.wiki.opencura.com/tools/cradle/resources/vue/typeahead-search.html)' has hardcoded references to `https://www.wikidata.org/w/api.php?callback=?` and therefore returns Wikidata items when typing. Once 'Q1' is entered for "instance of", the correct item is shown in the suggestion menu.

![CradleWorking](https://user-images.githubusercontent.com/383043/114478394-0e5a6f80-9bf6-11eb-9089-7d813e0512c8.png)

With all fields filled out, **[the item can be successfully created](https://furry.wiki.opencura.com/w/index.php?title=Item:Q13&action=history)** - a 200 was returned. However, when I did this, the 'working' circle to the right of 'Help' kept spinning (but this cleared when I edited one of the fields). If it intended to tell me it had succeeded, it did not.

---
As a secondary matter - I don't know if it matters at all, or where, but it seems incorrect:
In wikidata.js, function WikiData () , this.set_custom_api there is a line
> self.page_path = 'https:' + d.query.general.server + d.query.general.articlepath ;

However `d.query.general.server = "https://furry.wiki.opencura.com"`
...so this means `self.page_path = "https:https://furry.wiki.opencura.com/wiki/$1"` which seems incorrect.
It might have helped if using `d.query.general.servername` (`= "furry.wiki.opencura.com"`), but then it'd need `'https://'`

**Comment by GreenReaper** [comment]
I know this sounds hacky, but if it was searching for `t:(P\d+)` (after all, the 'wd' is 'wikidata', right?) then the direct props would have been detected in this case, and probably for others making up their own prefixes using the pattern started by Wikidata.

[Wikibooks suggests](https://en.wikibooks.org/wiki/SPARQL/Prefixes) the only other _built-in_ `t:` prefix is `hint:` which may not be used in ShEx - or it could be specifically excluded. [Bigdata's QueryHints wiki page](https://github.com/blazegraph/database/wiki/QueryHints) also suggests it is only "hint:Prior" with `t:P` - the P isn't followed by a number, so wouldn't match.

**Comment by GreenReaper** [comment]
Unfortunately I think such abbreviations will not work with the new version of federated props, that [proposes to use the Concept URI as the property identifier](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/700481/4/docs/adr/0019-federated-properties-prefix-ids-via-uris.md). Instead it may have to accept everything that can be a URL - or, more practically, everything up to a terminator.

**Comment by Vesihiisi** [comment]
> However, the component '[typeahead-search](https://furry.wiki.opencura.com/tools/cradle/resources/vue/typeahead-search.html)' has hardcoded references to `https://www.wikidata.org/w/api.php?callback=?` and therefore returns Wikidata items when typing. Once 'Q1' is entered for "instance of", the correct item is shown in the suggestion menu.


I just encountered this issue when working on https://metabase.wikibase.cloud/tools/cradle/?#/shex/E2 -- the suggestions all come from Wikidata.

![cradle-autofill-wikidata](https://user-images.githubusercontent.com/1749153/232073152-6f0f5089-1c58-4732-a8d7-dfbbb7f7c8b9.png)

**Comment by lokal-profil** [comment]
Seems to be https://github.com/wbstack/magnustools/blob/2c2e4128132ac7f943934fa909fa9da7b07e0138/public_html/resources/vue/typeahead-search.html#L118 and L135 causing that issue

**Comment by deer-wmde** [comment]
moved to https://phabricator.wikimedia.org/T357109
